"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - fl_abd_joint
          - fl_hip_joint
          - fl_knee_joint
          - fr_abd_joint
          - fr_hip_joint
          - fr_knee_joint
          - bl_abd_joint
          - bl_hip_joint
          - bl_knee_joint
          - br_abd_joint
          - br_hip_joint
          - br_knee_joint
      
      # constraints:
      #   goal_time: 0.01
      #   stopped_velocity_tolerance: 0.01

      # stop_trajectory_duration: 0.01

      gains:
        fl_abd_joint  : {p: 100, d: 6, i: 0.2}
        fl_hip_joint  : {p: 100, d: 6, i: 0.2}
        fl_knee_joint : {p: 100, d: 6, i: 0.2}
        fr_abd_joint  : {p: 100, d: 6, i: 0.2}
        fr_hip_joint  : {p: 100, d: 6, i: 0.2}
        fr_knee_joint : {p: 100, d: 6, i: 0.2}
        bl_abd_joint  : {p: 100, d: 6, i: 0.2}
        bl_hip_joint  : {p: 100, d: 6, i: 0.2}
        bl_knee_joint : {p: 100, d: 6, i: 0.2}
        br_abd_joint  : {p: 100, d: 6, i: 0.2}
        br_hip_joint  : {p: 100, d: 6, i: 0.2}
        br_knee_joint : {p: 100, d: 6, i: 0.2}
