"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - lf_hip_adapter_joint
          - lf_upper_leg_adapter_joint
          - lf_lower_leg_adapter_joint
          - rf_hip_adapter_joint
          - rf_upper_leg_adapter_joint
          - rf_lower_leg_adapter_joint
          - lh_hip_adapter_joint
          - lh_upper_leg_adapter_joint
          - lh_lower_leg_adapter_joint
          - rh_hip_adapter_joint
          - rh_upper_leg_adapter_joint
          - rh_lower_leg_adapter_joint

      gains:
        lf_hip_adapter_joint : {p: 180, d: 0.9, i: 20}
        lf_upper_leg_adapter_joint : {p: 180, d: 0.9, i: 20}
        lf_lower_leg_adapter_joint : {p: 180, d: 0.9, i: 20}
        rf_hip_adapter_joint : {p: 180, d: 0.9, i: 20}
        rf_upper_leg_adapter_joint : {p: 180, d: 0.9, i: 20}
        rf_lower_leg_adapter_joint : {p: 180, d: 0.9, i: 20}
        lh_hip_adapter_joint : {p: 180, d: 0.9, i: 20}
        lh_upper_leg_adapter_joint : {p: 180, d: 0.9, i: 20}
        lh_lower_leg_adapter_joint : {p: 180, d: 0.9, i: 20}
        rh_hip_adapter_joint : {p: 180, d: 0.9, i: 20}
        rh_upper_leg_adapter_joint : {p: 180, d: 0.9, i: 20}
        rh_lower_leg_adapter_joint : {p: 180, d: 0.9, i: 20}
