left_front:
  - LF_HAA
  - LF_HFE
  - LF_KFE
  - LF_ADAPTER_TO_FOOT

right_front:
  - RF_HAA
  - RF_HFE
  - RF_KFE
  - RF_ADAPTER_TO_FOOT

left_hind:
  - LH_HAA
  - LH_HFE
  - LH_KFE
  - LH_ADAPTER_TO_FOOT

right_hind:
  - RH_HAA
  - RH_HFE
  - RH_KFE
  - RH_ADAPTER_TO_FOOT