left_front:
  - B1_joint
  - B2_joint
  - B3_joint
  - B4_joint

right_front:
  - A1_joint
  - A2_joint
  - A3_joint
  - A4_joint

left_hind:
  - D1_joint
  - D2_joint
  - D3_joint
  - D4_joint

right_hind:
  - C1_joint
  - C2_joint
  - C3_joint
  - C4_joint