left_front:
  - lf_hip_adapter_joint
  - lf_upper_leg_adapter_joint
  - lf_lower_leg_adapter_joint
  - lf_foot_joint

right_front:
  - rf_hip_adapter_joint
  - rf_upper_leg_adapter_joint
  - rf_lower_leg_adapter_joint
  - rf_foot_joint

left_hind:
  - lh_hip_adapter_joint
  - lh_upper_leg_adapter_joint
  - lh_lower_leg_adapter_joint
  - lh_foot_joint

right_hind:
  - rh_hip_adapter_joint
  - rh_upper_leg_adapter_joint
  - rh_lower_leg_adapter_joint
  - rh_foot_joint