base: base
left_front:
  - LF_HIP
  - LF_THIGH
  - LF_SHANK
  - LF_FOOT

right_front:
  - RF_HIP
  - RF_THIGH
  - RF_SHANK
  - RF_FOOT

left_hind:
  - LH_HIP
  - LH_THIGH
  - LH_SHANK
  - LH_FOOT

right_hind:
  - RH_HIP
  - RH_THIGH
  - RH_SHANK
  - RH_FOOT